export const USER_LOGIN = 'USER_LOGIN'
export const USER_CLEAR = 'USER_CLEAR'

export const SET_NUTRIENT_NORMS = 'SET_NUTRIENT_NORMS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const SET_PRODUCT_CATEGORIES = 'SET_PRODUCT_CATEGORIES'